### ISSUE TITLE
Very similar to iOS interface

### ISSUE THREAD

**Issue by janroures** [abury/ABPadLockScreen#43]
My app has just been rejected because "the passcode screen may be confusingly similar to the iOS Passcode interface."

**Comment by abury** [comment]
Hi janroures
I'm sorry to hear that. There are a number of apps that use this module on the App Store already so this is not a universal problem.
There are many ways to customise the lock screen. Perhaps try to update the look of it and resubmit.

**Comment by janroures** [comment]
I know. The guys reviewing the apps are jerks :p sometimes I'd just like bomb apple HQ. Thx for your answer.

PS: this pod is so cool! great job!

**Comment by abury** [comment]
It can be tough to get it through sometimes. Thanks for letting me know though. Post back and let us know how you go in the end!

**Comment by rando128** [comment]
Mine got rejected too...

**Comment by janroures** [comment]
same reason?

**Comment by abury** [comment]
Can you show us what your implementations look like? I've seen quite a number of screens successfully submitted to the app store without issue.

**Comment by rando128** [comment]
Yes same reason. Snapshot below. I admit I didn't tweak it much :) I've resubmitted after customization.

![temp uttulxkb](https://cloud.githubusercontent.com/assets/1491835/9849252/5b25e42e-5ae9-11e5-8e64-6d5b7bd69de1.png)

**Comment by abury** [comment]
Yeah, with the transparent background it does look a lot like the system lock screen. Let me know how the resubmission goes :)

**Comment by rando128** [comment]
Got rejected again with this UI. Anyone can share a branding that passed the submission?

![temp cdhikggq](https://cloud.githubusercontent.com/assets/1491835/10257105/bcf6ca2c-6955-11e5-9768-c02459fecb2a.png)

**Comment by abury** [comment]
That's pretty bad form on their end. I suspect though the issue lies with the transparent background. I've never used that feature before (it was added by a PR :wink: ) 
This is an example of one that passed review

![image1](https://cloud.githubusercontent.com/assets/982276/10271386/f9adb16a-6b3f-11e5-8ee5-168da8348a5a.PNG)

I know @tuuky used it for 'Screen time - media manager' as well https://itunes.apple.com/us/app/screen-time-media-time-manager/id412387263?ls=1&mt=8
